source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationSetOptions.java
source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java

This to make it possible to either start calculations with or without this limit.

Added option to configure if WNB 25km calculation limit should be applied

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/Substance.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/ADMSSourceCharacteristics.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/BuoyancyType.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/EffluxType.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/SourceType.java

Also added more substances and AMBIENT to BuoyancyType.

Added SourceType to ADMS, and additonal safeValueOf methods.

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/ops/OPSLimits.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/building/BuildingLimits.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java

This way code that checks limits can be independently being developed from OPS and ADMS.
This change introduces the ADMSLimits file in this project.

Added interface building limits

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/ADMSSourceCharacteristics.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/EffluxType.java

Add known default for L1, and fixed minimum L1 limit.

Added L1/L2 variables to ADMSSourceCharacteristics

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/road/GML2SRMRoad.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
source/imaer-gml/src/test/resources/gml/v3_1/roundtrip/road_specific_and_custom.gml
source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/road_specific_and_custom.gml

Added a roundtrip test case for this as well, and adjusted the TestValidationAndEmissionHelper to supply a (default) emisssion factor for specific vehicles.

AER-107 Setting TimeUnit for custom and specific vehicles on import

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/road/GML2SRMRoad.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
source/imaer-gml/src/test/resources/gml/v3_1/roundtrip/road_specific_and_custom.gml
source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/road_specific_and_custom.gml

Added a roundtrip test case for this as well, and adjusted the TestValidationAndEmissionHelper to supply a (default) emisssion factor for specific vehicles.
(cherry picked from commit 7cc61f30dc1b844bda809719ea2f88d28f4889f6)

AER-107 Setting TimeUnit for custom and specific vehicles on import (#48)

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/ADMSSourceCharacteristics.java

Removed copyTo method. It's not used.

Added ADMS jet angle parameters

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/EmissionSourceType.java

No further changes other than adding a type

Add ADMS_ROAD type

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java

Values confirmed in Mattermost

Add ADMS road width constraints

---

source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/base/TimeUnit.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/road/RoadStandardEmissionFactorsKey.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/road/RoadStandardsInterpolationValues.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/ADMSRoadEmissionsCalculator.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/EmissionsCalculator.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/RoadEmissionFactorSupplier.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/SRMRoadEmissionsCalculator.java
source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/ADMSRoadEmissionsCalculatorTest.java
source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/EmissionsCalculatorTest.java
source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/SRMRoadEmissionsCalculatorTest.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/RoadValidationHelper.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/RoadValidator.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/RoadValidatorTest.java

Added interpolation mechanism for ADMS roads for standard vehicle types.
Doing both speed and gradient (gradient being part of AER-179, but while at it...)
This will break a project using this library, so needs a PR in our main project to be ready before merging.

AER-324 interpolation for ADMS road emission factors

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/ADMSRoadEmissionsCalculator.java
source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/ADMSRoadEmissionsCalculatorTest.java

Since it matters for gradient which direction you're going, we better take that into account.
Assumption is made that 50% of vehicles will go from A to B and from B to A if it's the direction BOTH.
Removed the measure bit as well. Not sure if this ever comes into play, but would make the code a bit more complex...

AER-330 Incorporating direction for ADMS road emissions

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/geojson/Polygon.java
source/imaer-util/src/main/java/nl/overheid/aerius/util/GeometryUtil.java
source/imaer-util/src/test/java/nl/overheid/aerius/util/GeometryUtilTest.java

Added method to convert polygon to convex polygon

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java

Min should be 1 and default 30 according to ADMS manual.

Fix min monin obukhow length min and default

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/ADMSSourceCharacteristics.java

width on road will be replaced by this, and removed in a follow up pr.

Add width to ADMS source characteristics

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/characteristics/GML2ADMSSourceCharacteristics.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/characteristics/GML2OPSSourceCharacteristics.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/road/GML2ADMSRoad.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/util/DiurnalVariationUtil.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/GMLVersionWriterV50.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/InlandRoute2GML.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/MaritimeRoute2GML.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/NSLDispersionLine2GML.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/Road2GML.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/SourceCharacteristics2GML.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/ToGMLUtil.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
source/imaer-gml/src/test/resources/gml/v5_0/roundtrip/adms_road_with_custom_diurnal_variation.gml
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/ADMSRoadEmissionSource.java
source/imaer-util/src/main/java/nl/overheid/aerius/util/gml/GMLIdUtil.java

Missing domain part for ADMS road.
Includes a roundtrip test for ADMS road with custom diurnal variation.
Also attempting to avoid some code duplication when it comes to getting/setting these properties.

AER-418 ADMS diurnal variation IMAER, pt 3

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/ScenarioSituation.java
source/imaer-shared/src/test/resources/json/ScenarioSituationMooringShipping.json
source/imaer-shared/src/test/resources/json/ScenarioSituationNSL.json
source/imaer-shared/src/test/resources/json/ScenarioSituationSourcesOnly.json

because we need those to transfer scenario data from connect to the worker via the fileservice.

Enable serialization of nsl measures to json

---

source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImaerImporter.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLValidateErrorsTest.java
source/imaer-gml/src/test/resources/gml/latest/validate/errors/fout_5235_netting_without_factor.gml
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java

Added a test case in the GMLValidateErrorsTest for this one as well (might have expected it in GMLValidateWarningsTest, but tbh that one should be refactored a bit).

AER-651 Added a warning when netting factor not supplied for netting situation

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLVersionReaderFactory.java
source/imaer-gml/src/main/java/nl/overheid/aerius/schematron/ImaerSchematronResourceBuilder.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/ImaerConstants.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/geo/HexagonZoomLevel.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/result/EmissionResultKey.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/scenario/CalculationMetaData.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/scenario/SituationMetaData.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/geometry/ReceptorUtil.java
source/imaer-xsd-server/src/main/webapp/WEB-INF/html/error.html
source/shared-geo/src/main/java/nl/overheid/aerius/geo/shared/BBox.java
source/shared-geo/src/test/java/nl/overheid/aerius/geo/shared/BBoxTest.java

* Fixes all Sonar issues classified as 'bug' or 'vulnerability'

AER-801 Sonar fixes

---

source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
source/imaer-gml/src/test/resources/gml/v5_1/roundtrip/nca_calculation_options.gml
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/NCACalculationOptions.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/RoadLocalFractionNO2Option.java
source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java

Also included some roundtrips to show how this would work, the GML requiring some more changes as we didn't have a roundtrip for NCA calculation options yet.

AER-965 road local fraction NO2 in NCACalculationOptions

---

source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farm/FarmLodging.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farmland/StandardFarmlandActivity.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/FarmEmissionFactorType.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/IsFarmEmissionFactorTypeObject.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmEmissionFactorTypeValidatorUtil.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmLodgingValidationHelper.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmLodgingValidator.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmlandValidationHelper.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmlandValidator.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/FarmLodgingValidatorTest.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/FarmlandValidatorTest.java

Also changed validation so these can be validated in a generic approach.
Not too sure about the interface with all the default methods, but it does seem to work based on the unittests...

New scail emission factor types

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationType.java

Required by https://github.com/aerius/AERIUS-II/pull/4772

AER-816 Added CUSTOM_RECEPTORS as CalculationType

---

source/imaer-gml/pom.xml
source/imaer-util/pom.xml
source/pom.xml

Version checking using `versions-maven-plugin` and `dependency-check-maven`.
Also made some plugin versions explicit.
Also updated some versions based on feedback from these.
WIP till after next release.

Versions checking and updating

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GML2Definitions.java
source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImaerImporter.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLValidateErrorsTest.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/BuildingValidator.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/DefinitionsValidator.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/ScenarioSituationValidator.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/BuildingValidatorTest.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/DefinitionsValidatorTest.java

Also some other validation related changes, like moving the CustomDiurnalVariation validation and introducing a new Validator that can help with validation a whole situation. 
That last class is intended for last-minute checks, like ensuring the objects we're about to calculate are actually valid (we already do this, but for sources only).

AER-824 building validation more strict

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/BuildingValidator.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/BuildingValidatorTest.java

Also checking on correct geometry type

AER-824 Added validation on circular buildings

---

source/imaer-util/src/main/java/nl/overheid/aerius/util/GeometryUtil.java
source/imaer-util/src/test/java/nl/overheid/aerius/util/GeometryUtilTest.java

Added unit test. (Removed dependency on WKTGeometry too)

Wrap invalid geometries to throw an AeriusException instead.

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationJobType.java

and add min and max situation validation information

AER-1379 add single scenario type

---

source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLCalculationSetOptionsReaderTest.java
source/imaer-gml/src/test/resources/gml/v5_1/roundtrip/nca_calculation_options.gml
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/ADMSOptions.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java
source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java

Also always write ADMS options affected when using demo mode to the GML (depletion, spatially variying roughness and, complex terrain)

Added Spatially Varying Roughness ADMS option

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java

- Adjusted minimum source height
- Added default source height and percent nox as no2

AER-1454 Updated ADMS default values

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java

- Updated SOURCE_HEIGHT_MINIMUM to be 0.001 instead of 0.0005

AER-1454 source height 0.0005 -> 0.001

---

source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
source/imaer-gml/src/test/resources/gml/v5_1/roundtrip/nca_calculation_options_quick_run.gml
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationMethod.java

- Add CalculationMethod QUICK_RUN
- Add roundtrip test for QUICK_RUN

AER-1748 CalculationMethod Quickrun

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLScenarioHelper.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLWriter.java

One method to construct the metadata input for an archive contribution GML, and one method to write the actual GML without having to supply a situation.

AER-2207 Added some help methods for archive contribution GMLs

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLValidator.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/GMLVersionWriterV50.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_1/togml/GMLVersionWriterV51.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLValidateErrorsTest.java

Therefore we should check if scenarioMetaData is not null as it's not required to have this information set.

AER-2449 constructArchiveMetaData does not set ScenarioMetaData

---

source/imaer-gml/pom.xml
source/imaer-shared/pom.xml
source/imaer-sonar-report/pom.xml
source/imaer-util/pom.xml
source/imaer-xsd-server-standalone/pom.xml
source/imaer-xsd-server/pom.xml
source/pom.xml
source/shared-geo/pom.xml

In preparation of upcoming release(s)

Release 5.1.3-1

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationRoadOPS.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/WNBCalculationOptions.java
source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java

Also improved some documentation and fixed some style warnings.

AER-2433 Added splitSubReceptorWork options to WNBCalculationOptions

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLReaderFactory.java

Also some qa improvements included.

AER-1036 log validation errors as debug since message is rethrown again and later logged if needed.

---

source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImaerImporter.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLCalculationSetOptionsReaderTest.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLReaderTest.java
source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/Theme.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationSetOptions.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/OwN2000CalculationOptions.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/WNBCalculationOptions.java
source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java

Deprecated Theme WNB to avoid breaking backward compatibility.

AER-2710 rename WNB to OWN2000

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationSetOptions.java

Field name should match method name owN200CalculationOptions exactly and old method getWnbCalculationOptions should have JsonProperty annotation

AER-2710 Fix json serialisation

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/road/CustomVehicles.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/BaseRoadEmissionsCalculator.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/ColdStartEmissionsCalculator.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/SubSourceEmissionsCalculator.java

AER-2846 - added vehicle type to CustomVehicle, that is needed to determine characteristics for cold start vehicles.

[AER-2774] Changes related to cold start emission calculations.

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/EntityReference.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/EntityType.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/NcaCustomCalculationPoint.java
source/imaer-shared/src/test/resources/json/NcaCustomCalculationPoint.json

- Updated NcaCustomCalculationPoints to include a list of entityReferences
- Updated JSON test file (tested in JsonRoundTripTest) to also include this new entityReferences

AER-2735 Link Habitat or Species to a custom assessment point

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/EntityReference.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/EntityType.java
source/imaer-shared/src/test/resources/json/NcaCustomCalculationPoint.json

- Added map of critical levels to EntityReference
- Added `CRITICAL_LEVEL_ENTITY` EntityType
- Updated NcaCustomCalculationPoint.json to include the new criticalLevels in the unit tests, and test an entity reference without a code

EntityReference update

---

source/imaer-util/src/main/java/nl/overheid/aerius/validation/DefinitionsValidator.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/DefinitionsValidatorTest.java

Now also allowing the exact limit instead of throwing an exception (similar to frontend in related project).

AER-2799 Relaxed validation on allowed time varying profile values

---

source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/CimlkCohesionValidatorTest.java

In this repository all usages now replace with CIMLK.

Removed dependencies on deprecated Theme RBL

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
source/imaer-shared/src/test/java/nl/overheid/aerius/shared/exception/ImaerExceptionReasonTest.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/ScenarioSituationValidator.java
source/imaer-util/src/main/java/nl/overheid/aerius/validation/SituationCohesionValidator.java
source/imaer-util/src/test/java/nl/overheid/aerius/validation/SituationCohesionValidatorTest.java

Most notably references between objects, like sources and buildings, and sources and time varying profiles. Should result in faster feedback when something is not right, preventing errors for calculations or incomplete GMLs.

AER-3740 situation cohesion validators

---

source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/mobile/v31/GML2OffRoad.java
source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/mobile/v40/GML2OffRoad.java

- Set diurnal profile to INUDSTRIAL_ACTIVITY for custom offroad mobile sources

AER-3719 Custom offroad mobile sources

---

source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/RoadEmissionSource.java
source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/road/RoadElevation.java

Part of https://aerius.atlassian.net/browse/AER-3738
Will allow consolidation of tunnel factor default setting into just one place.

Move default value for tunnel factor to RoadElevation
