- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/characteristics/GML2SourceCharacteristics.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/geo/OrientedEnvelope.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/GeometryUtil.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/ConstructPolygonTest.java
Building orientation is being based on North is 0 degree and clockwise.
For the code in the IMAER-Java project this has limited impact because the building itself is kept as polygon.
But for reading older GML files these should be interpreted as X-as counter-clockwise to be backward compatible.
> Changed builing orientation to be North clockwise based.

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/meteo/Meteo.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/meteo/MultiYearMeteo.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/meteo/SingleYearMeteo.java
That is, it's no longer abstract, but incorporates both start and end year. This way it replaces SingleYearMeteo and MultiYearMeteo. If start and end year are the same, it can be considered a single year meteo, but that shouldn't matter too much for most applications. 
Removed the opsFile to be part of the object as well: this is too model specific, and determining the correct files is something that can be done in the OPS part of AERIUS based on the start and end year (there's a certain structure to those file names).
This is in preparation of using meteo for ADMS and making it selectable in the UI.
Using @deprecated to avoid causing compilation errors in the Calculator repository.
> AER3-1038 Changed the structure that Meteo uses

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v2_0/metadata/CalculationMetadata.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v2_1/metadata/CalculationMetadata.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v2_2/metadata/CalculationMetadata.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v3_0/metadata/CalculationMetadata.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v3_1/metadata/CalculationMetadata.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/metadata/CalculationMetadata.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLReaderTest.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/Theme.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationSetOptions.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationType.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/Scenario.java
Because we get more themes that have similar calculation types it makes sense to remove the theme like types from CalculationType and add the Theme as a separate variable to Scenario.
This will make it easier to use the same calculation type among different themes.
> Introduced Theme to Scenario

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/road/GML2SRMRoad.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/togml/Road2GML.java
As it was, the mergingStandardVehicles list would only be kept for one property, which was not terribly useful...
Also ensured that the export order of standard vehicles is more predictable. Especially handy for roundtrip tests.
> AER3-1127 Correctly grouping standard vehicles for roads

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLConversionData.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLLegacyCodeConverter.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLLegacyCodesSupplier.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLVersionReaderFactory.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/conversion/PlanConversion.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/plan/GML2Plan.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/togml/SourceCharacteristics2GML.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/AssertGML.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
- source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/plan.gml
Plan emissionsources are not directly supported anymore. Hence the need to convert these types of sources to something else: generic emission sources.
With this change each activity ends up in it's own separate source. While it might be possible to merge activities into one source if the characteristics are the same, there was probably a reason why the activities were separate in the first place. It's easier for a user to merge the sources if he requires than to split the sources if already merged (because that would require knowing emission factors and original amounts being input).
> AER3-1161 Converting plan emission sources to generic sources on import

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/togml/InlandRoute2GML.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/togml/MaritimeRoute2GML.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/togml/SourceCharacteristics2GML.java
As it was, the ID's used for references weren't always the same as the ID of the object being referenced, since those objects would receive an ID that was guaranteed to be valid according to the definition (for instance, not starting with a number).
By using the same utility function for those ID's, we should arrive at the same result.
> Valid gml references

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
The order of the arguments did not match what is actually used in GMLConversionData (`new AeriusException(getReason(codeType), oldCode, returnCode, forSource)`).
> Corrected javadoc for some conversion ImaerExceptionReasons

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/AbstractGML2Specific.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/mobile/v31/GML2OffRoad.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/mobile/v40/GML2OffRoad.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/plan/GML2Plan.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/ship/v31/GML2InlandMooring.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/ship/v31/GML2InlandMooringForceWaterway.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/ship/v31/GML2MaritimeMooring.java
- source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/mooringinland.gml
- source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/mooringmaritime.gml
As it was the label for sources that were created for routes for mooring shipping for older IMAER versions (<= 3.1) were always empty. 
With this change, an attempt is made to get a label for these sources based on their context.
- Inland mooring routes get `[mooring source label]; Route [route index within the mooring source]`
- Maritime Inland mooring routes ('binnengaats') get `[mooring source label]; Route [route index within the mooring source]`
- Maritime maritime mooring routes get `Route [global route index]` (as these routes were re-usable in AERIUS-II between sources, this made a bit more sense).
> AER3-1224 Shipping mooring backwards comp. route names

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLConversionData.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/conversion/MobileSourceOffRoadConversion.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/mobile/v31/GML2OffRoad.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/base/conversion/MobileSourceOffRoadConversionTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
- source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/offroad.gml
- source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/offroad_idle_and_nh3.gml
- source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/offroad_non_idle.gml
- source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/offroad_with_specifications.gml
Where we used to determine operating hours based on fuel consumption for the old category (which also had a possible idle component), we are now doing it based on the fuel consumption of the new category. The assumption is made that the literFuelPerYear is correct (as we don't know if the user specified this based on experience or based on a 'handreiking'). So all we're doing now is converting the liters fuel used to a total number of operating hours, and any idle properties possibly specified by the user are not taken into account.
Numbers used in the unittests are the ones supplied by the 'actualisatieteam' for the corresponding categories.
> AER3-1238 Mobile source backwards compatibility change

- source/imaer-shared/src/main/java/nl/overheid/aerius/geo/shared/WGS84.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/EmissionSource.java
Intended for use with OPS .brn file, where sources can have different SRIDs
> AER3-887 EPSG code for WGS84

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/conversion/MobileSourceOffRoadConversion.java
Constructor was used to avoid compilation issues in other repository. Should be save to remove after some time (a few days).
> Remove deprecated constructor

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/CalculationPoint.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/CalculationPointType.java
NSLCaclulationPoint can also be part of GML therefor it should be added as type to CalculationPoint.
Fixes AER3-1332 where csv files imported cause an error when starting calculation because csv file is read as NSLCalculationPoint and when receiving at the server as part of a scenario to calculate it can't parse this type object causing it to crash.
> Fix adding support for NSLCalculationPoints Type

- source/imaer-shared/src/main/java/nl/overheid/aerius/geo/shared/BNGrid.java
The old definition (based on epsg.io) didn't cover england properly (bit in the south-east was cut off). The new defitiniton (based on spatialreference.org, and which is identical to our calculation boundary) does seem to cover UK properly.
> Correct bounds for BNGrid

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/geo/Geo2GeometryUtil.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/geo/Geometry2GML.java
- source/imaer-util/pom.xml
- source/imaer-util/src/main/java/nl/overheid/aerius/util/GeometryCalculatorImpl.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/GeometryUtil.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/EmissionSourceValidator.java
In 2016/2017 JTS moved to locationtech. With version 1.15 (nov 2017) the package names and maven groupIds were changed as well. Think now is a good time to switch along with it (gives some more options as well, which might help with the overlapping hexagon detection for instance). Should contain some performance improvements as well (though not too sure how that'll affect us).
This will probably break applications when using classes like GeometryUtil.
> Switched to newer JTS library (1.18.2)

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/OPSOptions.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java
The input value is written to gml instead of the label used in the control file to prevent empty values when using ACTUAL chemistry.
Rename field in chemistry enum to make the distinction more clear.
> AER-262 Fix empty value in results gml when using actual chemistry.

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/AbstractGML2Source.java
As it was, it would use the default characteristics for the ID in the GML, not the one that was possibly converted to the correct sector ID.
> Using correct sector ID for default sector characteristics

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/ADMSRoadEmissionsCalculator.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/RoadEmissionFactorSupplier.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/ADMSRoadEmissionsCalculatorTest.java
Emissions in test case get a bit high, but that's because they're about 10^7 times higher than what we got supplied as actual emission factors.
> AER-309 ensuring ADMS road total emission is in kg/year

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/road/ADMSRoadSideBarrierType.java
> "The type ‘other’ should always have the porosity 0%. At the moment it is 0% when you fill it in immediately, but when you choose another type and then change is to 'other', it keeps the porosity of the previous type. This is confusing for the user."
> AER-308 - Use a default porosity for OTHER

- source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImaerImporter.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/AssertGML.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
- source/pom.xml
This reuse of forks in the surefire plugin causes objects to be reused over tests.
However these objects can change between tests leading to test to fail if they use the cached version.
> No reuse in tests causing objects to be cached

- .github/workflows/build.yml
By using the new `pull_request_target` the workflow files from the base branch will be used,
making sure secrets won't be leaked.
> GitHub Action: Allow PRs to properly run workflows

- .github/workflows/build.yml
Normally this should be detected automatically by the Sonar Scanner, but 
since we moved to `pull_request_target` this doesn't work.
The Sonar Scanner might need an update or something else is going on.
By providing it we use the setup as we use for the AERIUS private repo 
in combination with Jenkins.
> GitHub Action: Explicitly add PR information to Sonar analysis

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java
Requested by Jess: The temperature range should be updated - it currently allows a range from -100 to 60 C but that should be a range from -100 to 5000 C
> AER-449 Updated temperature range for ADMS

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GML2Definitions.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/togml/GMLVersionWriterV40.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/GMLVersionWriterV50.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLValidateErrorsTest.java
- source/imaer-gml/src/test/resources/gml/v4_0/roundtrip/industry_with_custom_diurnal_variation.gml
- source/imaer-gml/src/test/resources/gml/v5_0/roundtrip/industry_with_custom_diurnal_variation.gml
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/CustomDiurnalVariation.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/CustomDiurnalVariationType.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/OPSSourceCharacteristics.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/SourceCharacteristics.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/domain/JsonRoundTripTest.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/domain/v2/characteristics/CustomDiurnalVariationTypeTest.java
- source/imaer-shared/src/test/resources/json/ADMSRoadEmissionSource.json
- source/imaer-shared/src/test/resources/json/GenericADMSEmissionSource.json
- source/imaer-shared/src/test/resources/json/GenericEmissionSource.json
Moved custom diurnal variation field to `SourceCharacteristics` so ADMS version can use it as well.
Introduced new type for custom diurnal variation for the 3-day profile.
Changed the average value as we expect it to 10000.
Changed the domain object to use doubles instead of integers (as discussed).
TODO in next PR: change IMAER to use doubles and incorporate custom diurnal variation in ADMS source characteristics and road objects.
> AER-418 ADMS diurnal variation IMAER, pt 1

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLScenarioHelper.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/road/GML2ADMSRoad.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/Road2GML.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/Source2GML.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/ADMSRoadEmissionSource.java
The definitions (and thus the custom diurnal variation profiles) weren't properly exported yet when using `GMLScenarioHelper`.
Also ensured that the main domain ADMS road object uses the properties for diurnal variation available in `ADMSSourceCharacteristics`.
> Diurnal variation adjustments

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/ScenarioSituation.java
- source/imaer-shared/src/test/resources/json/ScenarioSituationMooringShipping.json
- source/imaer-shared/src/test/resources/json/ScenarioSituationNSL.json
- source/imaer-shared/src/test/resources/json/ScenarioSituationSourcesOnly.json
This should prevent the need for nullpointer checks (though the object could still be set to null explicitly somewhere, or be absent when deserializing json).
> Ensuring definitions get created for ScenarioSituation

- source/imaer-shared/src/main/java/nl/overheid/aerius/geo/shared/BNGrid.java
Increase max zoom level from 13 to 15, which seems to be the maximum possible (at 16, tiles won't load)
> Increase BNG zoom level to the max possible

- source/imaer-gml/pom.xml
- source/imaer-shared/pom.xml
- source/imaer-sonar-report/pom.xml
- source/imaer-util/pom.xml
- source/imaer-xsd-server-standalone/pom.xml
- source/imaer-xsd-server/pom.xml
- source/pom.xml
In preparation of future development.
This version does assume that there won't be actual IMAER changes. If that is the case, the new version might well be something like 5.1 or 5.0.1, as IMAER-java version is tightly connected to the actual IMAER version.
> Update version to 5.0.0-2-SNAPSHOT

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/geo/Geo2GeometryUtil.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLValidateErrorsTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/base/Geo2GeometryUtilTest.java
- source/imaer-gml/src/test/resources/gml/latest/validate/errors/fout_666_unknown_error.gml
When a polygon is not closed, an `IllegalArgumentException` is thrown by JTS which is converted to a AeriusException with reason Internal Error. This change catches the IllegalArgumentException and converts it to a AeriusException with reason "The GML contains an invalid geometry", and includes the offending emission source ID.
> AER-333 Throw correct exception when polygon is not closed

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/EmissionSourceType.java
AER-619 implements a preview component for "Medium Combustion Plants", this emission source type, which may be changed in some way later, adds a source type for it.
> AER-619 - Add MEDIUM_COMBUSTION_PLANT emission source type

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/result/GML2Result.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/result/IsGmlSubPoint.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/result/SubPoint.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLReaderTest.java
As it was, an error would occur when reading a GML containing SubPoints.
Updated GMLReaderTest so it should pick up on errors in the reader during tests from now on.
> AER-690 Properly handling subpoints on import

- source/imaer-shared/src/main/java/nl/overheid/aerius/geo/shared/BNGrid.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/geo/shared/EPSG.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/geo/shared/RDNew.java
Apparently the BNGrid bounds specified here do not contain the entire of Northern Ireland. Updated the bounds to match the calculation boundary. The bounds are only used in OpenLayers. I also removed some settings that we no longer used in AERIUS (and not sure if those are still the correct values...)
> AER-709 Update BNGrid bounds

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/characteristics/GML2ADMSSourceCharacteristics.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/characteristics/IsGmlADMSSourceCharacteristics.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/source/characteristics/ADMSSourceCharacteristics.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/SourceCharacteristics2GML.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/ADMSSourceCharacteristics.java
Never added this property to actual IMAER, so any GML that would be exported with the massFlux property would be invalid w.r.t. the XSD. As we're not supporting the mass efflux type any more, we might as well get rid of the property while we're still in 5.0 territory.
The field in the domain object ADMSSourceCharacteristics itself hasn't been removed but deprecated, so this shouldn't pose any compatibility issues.
> AER-361 Deprecated massflux property in IMAER-java

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLCalculationSetOptionsReader.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLCalculationSetOptionsReaderTest.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
It should fail less on parts of the structure that are option (for instance, max range is optional, and shouldn't result in an error when not available).
Also included some tests that show behaviour (some of which were failing with the old code).
Also removed reading the stacking option, as I don't think it's something that we want to import from GML (for now at least).
> AER-722 Made GMLCalculationSetOptionsReader more robust

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/ScenarioSituation.java
- source/imaer-shared/src/test/resources/json/ScenarioSituationNSL.json
The corrections are needed when serializing because the scenario is stored as a file when sending the calculation task.
> AER-795 serialize the list of NSL corrections so they can be included in the calculation.

- source/imaer-util/src/main/java/nl/overheid/aerius/util/GeometryUtil.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/GeometryUtilTest.java
As it was, an ArrayIndexOutOfBoundsException would occur when a polygon with any number of holes would be supplied when converting from AERIUS to JTS objects.
> Fix issue with creating polygons with holes

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/ScenarioSituation.java
Getting a string id with "0." feels weird therefor remove that part.
> Generate a sane id by removing the 0. part of the generated number.

- source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImaerImporter.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/base/Geo2GeometryUtilTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/test/GMLTestDomain.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/geo/ReceptorGridSettings.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/geometry/ReceptorUtilTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/GeometryUtilTest.java
- source/shared-geo/src/main/java/nl/overheid/aerius/geo/shared/EPSG.java
- source/shared-geo/src/main/java/nl/overheid/aerius/geo/shared/EPSGProxy.java
- source/shared-geo/src/main/java/nl/overheid/aerius/shared/geo/EPSG.java
EPSG only needed to contain the SRID code. The other properties are specific for the UI and not needed here. Kept backward compatible for now. When this change is added the depending code can start using the new enum
> Simplified EPSG by introducing an new enum variant

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farmland/AbstractFarmlandActivity.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farmland/CustomFarmlandActivity.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farmland/FarmlandActivityVisitor.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farmland/StandardFarmlandActivity.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/FarmlandEmissionsCalculator.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/FarmlandEmissionsCalculatorTest.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmLodgingValidator.java
* Emissions weren't set for the Farmland subsources (FarmlandActivity).
* `numberOfDays ` were erased when they were expected and specified. Now only erased when they're not expected.
AER-868, AER-873, AER-876
> FarmlandActivity emission calculations and bugfix

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/lodging/GML2Farm.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmLodgingValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmlandValidator.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/FarmLodgingValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/FarmlandValidatorTest.java
The unknown farm emission factor type is purely something that can occur when importing GML (in our domain code it's already an enum, so harder to get wrong). The other reasons are triggered during normal validation, and can also occur on wrong input within our application (unexpected UI behaviour).
Also turns out the wrong reason was used...
> Changed error codes to be more consistent

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/CalculationPointVisitor.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/NSLCalculationPoint.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/point/NcaCustomCalculationPoint.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/CalculationPointDuplicator.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/CalculationPointDuplicatorTest.java
Used the CalculationPointVisitor, that has been updated with some missing types, so using `calculationPointFeature.accept(duplicator)` should be enough to duplicate a point (without it's results). Methods are protected with the idea that this should make it easier to override any of the types, in which case this class can be extended for the appropriate type (no longer visitor pattern in that case, but wouldn't know how else to do that with types not available in this library).
> Introduced a CalculationPointDuplicator

- source/imaer-util/src/main/java/nl/overheid/aerius/validation/ManureStorageValidator.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/ManureStorageValidatorTest.java
For custom manure storage it should be possible to specify a kg/y emission factor (in which case it's also directly the total kg/y emission).
> Allow emission factor type PER_YEAR for manure storage

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLMetaDataReader.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLScenarioHelper.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLValidator.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/InternalGMLWriter.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/MetaDataInput.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/togml/GMLVersionWriterV50.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_1/togml/GMLVersionWriterV51.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLReaderTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLWriterTest.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/Scenario.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/ScenarioMetaData.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/ScenarioSituation.java
Moved reference from ScenarioMetaData to ScenarioSituation, and using that reference to set the references in GML.
Kept the old location in a deprecated state for easier transition.
> AER-941 gml reference per situation

- source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImaerImporter.java
It seems like the reference (on the situation) is not set during import. But maybe this should be fixed somewhere else?
> Add the reference to the situation during import

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLMetaDataReader.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLWriter.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/ImaerConstants.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationSetOptions.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/scenario/SituationType.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/ADMSSourceCharacteristics.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/ScenarioMetaData.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmLodgingValidationHelper.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmlandValidationHelper.java
With recent release, it's time to clean up a bit.
Leftovers:
- AeriusGMLVersion (needs a decision if we want to remove these at some point)
- MassFlux in ADMSSourceCharacteristics (still used in live code, needs a proper decision)
- EmissionValueKey (still used in live code, but perhaps can limit how it's used some more)
> Remove more deprecated stuff

- source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImaerImporter.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImportOption.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/schematron/EmissionSourceSchematronVisitor.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/schematron/ImaerSchematronValidator.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/NSLMeasureValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/RoadValidator.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/NSLMeasureValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/RoadValidatorTest.java
These are validations that are currently handled by schematron. If we want to remove schematron, we better make sure those validations are still around.
Also deprecated the classes that are most likely used outside of the library when it comes to schematron use.
This is step 1 when it comes to removing schematron.
> Added validations to replace schematron

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/SubReceptorsMode.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/WNBCalculationOptions.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java
- Removed disableSubreceptors
- Added subReceptorsMode with ENABLED_RECEPTORS_ONLY (wnb default, not selectable in Analysis), ENABLED, ENABLED_OUTSIDE_HABITATS, DISABLED (analysis default)
- Added subReceptorZoomLevel to determine the zoom level
> AER-1047 Add subreceptors options

- source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/ops/OPSLimits.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/ADMSCharacteristicsValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/CharacteristicsValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/GenericSourceValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/OPSCharacteristicsValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/SourceValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/ValidationVisitor.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/ADMSCharacteristicsValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/BuildingValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/CIMLKMeasureValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/CharacteristicsValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/DefinitionsValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/FarmLodgingValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/FarmlandValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/ManureStorageValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/MooringInlandShippingValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/MooringMaritimeShippingValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/OPSCharacteristicsValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/OffRoadValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/PlanValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/RoadValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/RouteInlandShippingValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/RouteMaritimeShippingValidatorTest.java
We didn't validate characteristics in this generic part yet (only on model objects, which is a bit limited and late in the process), so had to add some new validators.
Tbh the heat capacity isn't directly part of the issue, so that can be considered a bonus (felt wrong to just do something for OPS and leave ADMS hanging).
> AER-1619 heat content (and heat capacity) validation

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/archive/ArchiveMetaData.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/archive/ArchiveProject.java
- source/imaer-shared/src/main/resources/nl/overheid/aerius/ImaerShared.gwt.xml
- source/imaer-shared/src/main/resources/nl/overheid/aerius/super/java/time/ZonedDateTime.java
ArchiveMetaData contains ZonedDateTime, and that is not emulated by GWT apparantly. To avoid having to resort to some other way (string perhaps?), we might as well exclude some packages, as these shouldn't be serialized to GWT code anyway.
> Excluding some packages from GWT

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLScenarioHelper.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/IsArchiveMetadata.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/OffsetDateTimeAdapter.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_1/metadata/ArchiveMetadata.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/archive/ArchiveMetaData.java
ZonedDateTime can include a identifier for the zone, but that isn't actually allowed. Turns out, if you don't have a zone ID specified in the string when parsing it, you'll end up with a zoned date time that does not contain one and when you format that again, you end up with something that's valid for offset date time as well (which is why the test case was succesful...)
> Changed ZonedDateTime to OffsetDateTime for archive retrieval date

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLWriter.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/InternalGMLWriter.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/AeriusGMLVersion.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLSchemaFactory.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLVersionReaderFactory.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLVersionWriterFactory.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v0_5/GMLReaderFactoryV05.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v0_5/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v1_0/GMLReaderFactoryV10.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v1_0/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v1_1/GMLReaderFactoryV11.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v1_1/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v2_0/GMLReaderFactoryV20.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v2_1/GMLReaderFactoryV21.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v2_1/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v2_2/GMLReaderFactoryV22.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v2_2/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v3_0/GMLReaderFactoryV30.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v3_0/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v3_1/GMLReaderFactoryV31.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v3_1/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/GMLReaderFactoryV40.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v4_0/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/GMLReaderFactoryV50.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_0/base/CalculatorSchema.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_1/GMLReaderFactoryV51.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v5_1/base/CalculatorSchema.java
By setting the schema on the marshaller, any XSD violations should be caught before invalid GMLs end up at the user.
This will cause some unittests to fail upstream, but that's for later concern.
> AER-2477 Validate by schema when writing GML

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLWriter.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/UnsupportedFeaturesTest.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/EmissionValueKey.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationJobType.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/ValidationHelper.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/ImaerFileUtilTest.java
Deprecate methods that construct filename. That logic should not be part of GMLWriter. Also some small codestyle improvements. Removed deprecated from EmissionValueKey as it was intended to be deprecated, but that is not the case at the moment.
> Added method to GMLWriter to pass full filename

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/EmissionSourceType.java
Since there is no other simple way to distinguish between these types on the client, we need to add another emission source type.
> AER-2772 - Split up cold start types

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/EmissionSourceType.java
GWT compile does not like it apparantly, at least not on build server.
Not sure if it has to be removed from all places in imaer-shared. Error during compile only hinted at this one, if this doesn't fix it i'll remove it from all.
> Removed forRemoval from deprecated annotation

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/EmissionSourceVisitor.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/FarmLodgingEmissionSource.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farm/AdditionalLodgingSystem.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farm/CustomFarmLodging.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farm/FarmLodging.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farm/LodgingFodderMeasure.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farm/LodgingSystem.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farm/ReductiveLodgingSystem.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/farm/StandardFarmLodging.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/FarmAnimalHousingEmissionsCalculator.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/FarmLodgingEmissionFactorSupplier.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/FarmLodgingEmissionsCalculator.java
GWT doesn't seem to like:
- forRemoval on Deprecated.
- InstanceOf and cast method usage. It both breaks code server compilation.
> Fix GWT causing issues

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java
Volume source default should be 0.0005 and other sources default should be 0.0.
> AER-1815 Added separate minimum height for source volumes, and changed defaults

- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLCalculationSetOptionsReaderTest.java
- source/imaer-gml/src/test/resources/gml/v5_1/roundtrip/nca_calculation_options.gml
- source/imaer-gml/src/test/resources/gml/v5_1/roundtrip/nca_calculation_options_quick_run.gml
- source/imaer-gml/src/test/resources/gml/v6_0/roundtrip/nca_calculation_options.gml
- source/imaer-gml/src/test/resources/gml/v6_0/roundtrip/nca_calculation_options_quick_run.gml
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/ADMSOptions.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/MetDatasetType.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/NCACalculationOptions.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java
Added MetDatasetType enum, and properties in ADMSOptions to support the new met site selection (dataset type and years). Deprecated met site properties on NCACalculationOptions: we never really used these.
> AER-2918 Met site changes

- source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmAnimalHousingValidationHelper.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/FarmAnimalHousingValidator.java
Data apparantly also contains additional systems that should only be used for one specific housing category. As that is more specific, it's better to always check on housing category over the animal category.
> AER-2979 Validating additional systems based on housing

- .github/workflows/on-pull_request-opened-synchronize-reopened.yml
- .github/workflows/on-push.yml
- .github/workflows/on-release-published.yml
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/ExternalEntitiesDisabledTest.java
Release already fails if this is the case, so makes more sense to fail when a PR introduces new failing tests. (noticed some tests failing, thought it already worked this way)
> Changed PR github action to fail when test fails

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/lodging/GML2Farm.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
- source/imaer-gml/src/test/resources/gml/v5_1/roundtrip/farm_no_conversion.gml
- source/imaer-gml/src/test/resources/gml/v6_0/roundtrip/farm_no_conversion.gml
Instead of an empty description, the description should now contain the main codes used in the old lodging definition. Only the main one, not any of the additional stuff, that would just get messy.
> AER-2858 description when farm lodging could not be converted

- source/imaer-gml/src/main/java/nl/overheid/aerius/importer/ImaerImporter.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/AssertGML.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
- source/imaer-gml/src/test/resources/gml/v5_0/roundtrip/industry_with_circular_building.gml
- source/imaer-gml/src/test/resources/gml/v5_1/roundtrip/industry_with_circular_building.gml
- source/imaer-gml/src/test/resources/gml/v6_0/roundtrip/industry_with_circular_building.gml
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/ops/OPSLimits.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/building/BuildingLimits.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/BuildingValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/ScenarioSituationValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/ValidationHelper.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/BuildingValidatorTest.java
This change also means validation on import gets a bit stricter, and OPS characteristics based applications won't allow circular buildings anymore (which they shouldn't anyway).
> AER-2978 Validation on building radius

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/ops/OPSLimits.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/building/BuildingLimits.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/BuildingValidator.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/BuildingValidatorTest.java
NL (OPS) does not want errors for upper limits, but wants warnings instead. Bit annoying, but this solution should work for that requirement. Also applied it to diameter, though NL does not really use that. Felt too weird to call it 'isBuildingHeightUpperLimitWarning' however, so went with this.
> AER-2978 Possibility to use warnings for building upper limits

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/MetDatasetType.java
Better keep it consistent while we still can.
> Consistent naming for MetDatasetType

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/ADMSCharacteristicsValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/CharacteristicsValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/OPSCharacteristicsValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/SourceValidator.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/ADMSCharacteristicsValidatorTest.java
- source/imaer-util/src/test/java/nl/overheid/aerius/validation/OPSCharacteristicsValidatorTest.java
That is, when characteristics dictate certain source types, the geometry should match it.
Also added a test on maximum vertices in the case of a polygon (area or surface).
> AER-2977 Geometry validation for ADMS + max vertices

- source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/FarmAnimalHousingEmissionFactorSupplier.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/FarmAnimalHousingEmissionsCalculator.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/FarmAnimalHousingEmissionsCalculatorTest.java
Basic housing is now based on animal housing category instead of the animal type. This is due to some animal types having multiple basic animal housing categories. Similarly, additional system factors are now based on animal housing category instead of the animal type. This is due to having different reduction factors for some animal housing + additional system combinations. Implementations will have to be adjusted accordingly.
> AER-3128 Animal housing less animal type based

- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/AssertGML.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/EmissionSourceVisitor.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/exception/ImaerExceptionReason.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/EmissionSourceValidator.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/SubSourceExpectsEmissionsVisitor.java
Using visitor to tell which subsources are expected to have emissions, beats having instanceof checks and is more explicit. Easy to adjust as well if it turns out most shipping sources have no emissions anyway if that turns out to be a thing.
> AER-3132 Warning when subsource has no emissions

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLWriter.java
Deprecated the old method so we can get rid of it at a later stage.
> AER-3167 writing archive contribution content directly to supplied file

- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLValidateErrorsTest.java
- source/imaer-gml/src/test/resources/gml/latest/validate/errors/fout_multiple_errors.gml
For future changes, where we might want to filter out the first one, or group based on location. It's also the original test case.
> Extended existing test slightly for xsd errors

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/SubSourceEmissionsCalculator.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/ColdStartEmissionsCalculatorTest.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/SubSourceEmissionsCalculatorTest.java
The cold start emissions calculator should return the emissions in kg/Year (it was g/year).
> AER-3178 Fix cold start SubSourceEmissionsCalculator

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLWriter.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/InternalGMLWriter.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLVersionWriterFactory.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v6_0/togml/GMLVersionWriterV60.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/v6_0/togml/Result2GML.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLReaderTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLWriterPerformanceTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLWriterTest.java
- source/imaer-gml/src/test/resources/gml/v6_0/test_receptors_no_representation.gml
Change is backward compatible.
> AER-2804 Added option to not add receptor hexagon representation in results in GML

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/scenario/ScenarioSituationResults.java
Than the calculation id can be used to retrieve the results to put in the GML. But we don't want to serialize results in this class as those are not needed, but only add to the message load.
> AER-2804 serialize ScenarionSituationResults to be ably to pass calculation id via message bus

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/NCACalculationOptions.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/ProjectCategory.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java
- Added ProjectCategory enum
- Added ProjectCategory to NCACalculationOptions
- Added ProjectCategory to OptionsMetadataUtil and -test
> AER-3210 Added ProjectCategory enum

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculatedSnapshotValues.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationSetOptions.java
- source/imaer-util/src/main/java/nl/overheid/aerius/util/OptionsMetadataUtil.java
- source/imaer-util/src/test/java/nl/overheid/aerius/util/OptionsMetadataUtilTest.java
Reasoning for putting it in CalculationSetOptions and the generic metadata section in IMAER is that its least changes. Conceptually it makes less sense as it's not a value that a user should generally alter/supply. But that's similar to OPS version that's also present in options/metadata I guess? Not too sure about both the reasoning and the term CalculatedSnapshotValues, suggestions are welcome.
> AER-3433 keep track of calculated snapshot values

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/ADMSRoadEmissionsCalculator.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/emissions/ADMSRoadEmissionsCalculatorTest.java
Not much point in doing interpolation if the result will just be multiplied with 0 anyway.
Performance change, shouldn't have effect on results.
> Avoid emission calculation for 0 vehicles

- source/imaer-gml/src/test/java/nl/overheid/aerius/test/TestValidationAndEmissionHelper.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/source/EmissionSourceVisitor.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/emissions/EmissionFactorSupplier.java
- source/imaer-util/src/main/java/nl/overheid/aerius/validation/ValidationHelper.java
Changed some default methods to non-defaults (should be implemented by now), and made some methods default and indicated that they are deprecated through annotation and comment.
Should make it easier to remove these methods in upstream project(s).
> Preparing for farm lodging removal

- source/imaer-gml/pom.xml
- source/pom.xml
The way we use streamflyer we don't actually use commons-io in that library, but we do use it ourselves. Would rather get rid of streamflyer at some point, but that's more complicated.
> Avoid including an old commons-io version

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/GMLCalculationSetOptionsReader.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLWriterTest.java
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/calculation/CalculationSetOptions.java
As it was, the calculation method was in charge of determining if the maximum range was relevant. UK however allows users to input the maximum range for FORMAL_ASSESSMENT, so this no longer holds.
Should be safe to do it like this: the option should be explicitly set when calculating in calculator, and that should override any value that was erronously read. The default value (false) also makes sense for NL, where the only options at the moment are custom points and formal assessment anyway.
> AER-3679 Explicitly state that maximum range is relevant

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/geo/HexagonZoomLevel.java
All fields can (and should) be reconstructed using level and level1Surface
In the (eventual) parser code, this class is handled by a custom parser which does ^ that, and so all of the other fields can be ignored and left out of the json.
Added final to the fields because the GWT constructor is no longer necessary
> Ignore a bunch of nonsense that needn't be in json

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/v2/characteristics/adms/ADMSLimits.java
As far as I could tell, this is only used in frontend for display purposes.
> AER-3666 Change precision for ADMS building values

- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/AssertGML.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLOldVersionTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLReaderTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLRoundtripTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLWriterPerformanceTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/GMLWriterTest.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/test/GMLTestDomain.java
- source/imaer-gml/src/test/resources/gml/v5_1/roundtrip/archive_metadata.gml
- source/imaer-gml/src/test/resources/gml/v6_0/roundtrip/archive_metadata.gml
- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/geo/ReceptorGridSettings.java
- source/imaer-shared/src/test/java/nl/overheid/aerius/shared/geometry/ReceptorUtilTest.java
Since the values of ReceptorGridSettings don't change they can be hard-coded. Breaking change: Changes `RecetorSettingsGrid` from a class into a enum.
> Refactor ReceptorGridSettings into an enum

- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/AbstractGML2Source.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLCharacteristicsSupplier.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/GMLConversionData.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/mobile/v31/GML2OffRoad.java
- source/imaer-gml/src/main/java/nl/overheid/aerius/gml/base/source/mobile/v40/GML2OffRoad.java
- source/imaer-gml/src/test/java/nl/overheid/aerius/gml/AssertGML.java
For ADMS it matters what the geometry type is. Or rather, it matters what the ADMS source type is, but the default for that can be based on geometry type. And since geometry type is fairly generic... Default methods in GMLCharacteristicsSupplier for easier conversion (that's the idea behind it at least).
> AER-3735 default characteristics also determined by geometry type

- source/imaer-shared/src/main/java/nl/overheid/aerius/shared/domain/ops/OPSLimits.java
Also updated the emission height to match the OPS implementation and set it here to 5000.
> AER-3991 spread max is 5000 included.
